const mathMap = {
  إيبسلون: 'EPSILON',
  // "": "acosh",
  // "": "asinh",
  // "": "atan2",
  // "": "atanh",
  // "": "cbrt",
  عصس32: 'clz32', // compute leading zeros عد الأصفار السابقة
  // "": "cosh",
  أسي_ط1: 'expm1',
  // "": "fround",
  ضرب_ص: 'imul',
  // "": "sinh",
  // "": "tanh",
  // "": "trunc",
  أرض: 'floor',
  أس: 'pow',
  أسي: 'exp',
  إشارة: 'sign',
  تقريب: 'round',
  جا: 'sin',
  جتا: 'cos',
  جتاع: 'acos',
  جزر: 'sqrt',
  جزر1_2: 'SQRT1_2',
  جزر2: 'SQRT2',
  حاع: 'asin',
  سقف: 'ceil',
  صغرى: 'min',
  ط: 'PI',
  ظا: 'tan',
  ظاع: 'atan',
  عشوائي: 'random',
  عطمى: 'max',
  لو: 'log',
  لو10: 'log10',
  لو10هـ: 'LOG10E',
  لو1ب: 'log1p',
  لو2: 'log2',
  لو2هـ: 'LOG2E',
  لوهـ10: 'LN10',
  لوهـ2: 'LN2',
  مطلق: 'abs',
  هـ: 'E',
  وتر: 'hypot',
};

module.exports = ['Math', mathMap];
