
const stringPrototype = {
  طول: "length",
  عند: "at",
  "":  "charAt",
  "":  "charCodeAt",
  "":  "codePointAt",
  "":  "concat",
  "":  "includes",
  "":  "endsWith",
  "":  "indexOf",
  "":  "lastIndexOf",
  "":  "localeCompare",
  "":  "match",
  "":  "matchAll",
  "":  "normalize",
  "":  "padEnd",
  "":  "padStart",
  "":  "repeat",
  "":  "replace",
  "":  "replaceAll",
  "":  "search",
  "":  "slice",
  "":  "split",
  "":  "startsWith",
  "":  "substr",
  "":  "substring",
  "":  "toLocaleLowerCase",
  "":  "toLocaleUpperCase",
  "":  "toLowerCase",
  "":  "toString",
  "":  "toUpperCase",
  "":  "trim",
  "":  "trimStart",
  "":  "trimEnd",
  "":  "valueOf",
  "":  "String.prototype.@@iterator()",
  "":  "anchor",
  "":  "big",
  "":  "blink",
  "":  "bold",
  "":  "fixed",
  "":  "fontcolor",
  "":  "fontsize",
  "":  "italics",
  "":  "link",
  "":  "small",
  "":  "strike",
  "":  "sub",
  "":  "sup",
  "":  "String.prototype[@@iterator]()",
  "":  "anchor",
  "":  "at",
  "":  "big",
  "":  "blink",
  "":  "bold",
  "":  "charAt",
  "":  "charCodeAt",
  "":  "codePointAt",
  "":  "concat",
  "":  "endsWith",
  "":  "fixed",
  "":  "fontcolor",
  "":  "fontsize",
  "":  "includes",
  "":  "indexOf",
  "":  "italics",
  "":  "lastIndexOf",
  "":  "link",
  "":  "localeCompare",
  "":  "match",
  "":  "matchAll",
  "":  "normalize",
  "":  "padEnd",
  "":  "padStart",
  "":  "repeat",
  "":  "replace",
  "":  "replaceAll",
  "":  "search",
  "":  "slice",
  "":  "small",
  "":  "split",
  "":  "startsWith",
  "":  "strike",
  "":  "sub",
  "":  "substr",
  "":  "substring",
  "":  "sup",
  "":  "toLocaleLowerCase",
  "":  "toLocaleUpperCase",
  "":  "toLowerCase",
  "":  "toSource",
  "":  "toString",
  "":  "toUpperCase",
  "":  "trim",
  "":  "trimEnd",
  "":  "trimStart",
  "":  "valueOf"
};


const stringMap = {
  "من_كود_الحرف": "fromCharCode",
  " ": "fromCodePoint",
  "": "raw",
};

export default ["String", stringMap, { constructMap: stringPrototype }];

