// translation map for keywords
exports._break = 'توقف';
exports._case = 'حالة';
exports._catch = 'اكتشف';
exports._continue = 'اسمتر';
exports._debugger = 'فاحص';
exports._default = 'افتراضي';
exports._do = 'افعل';
exports._else = 'وإلا';
exports._finally = 'في_النهاية';
exports._for = 'لكل';
exports._function = 'دالة';
exports._if = 'لو';
exports._return = 'ارجع';
exports._switch = 'بدائل';
exports._throw = 'اقذف';
exports._try = 'حاول';
exports._var = 'متغير';
exports._const = 'ثابت';
exports._while = 'بينما';
exports._with = 'مع';
exports._new = 'انشئ';
exports._this = 'هذا';
exports._super = 'مشرف';
exports._class = 'فئة';
exports._extends = 'امتداد';
exports._export = 'تصدير';
exports._import = 'استيراد';
exports._undefined = 'غير_معرف';
exports._null = 'جفاء';
exports._true = 'حق';
exports._false = 'باطل';
exports._instanceof = 'عينة_من';
exports._typeof = 'نوع';
exports._void = 'فارغ';
exports._delete = 'امح';
exports._let = 'عرف';
exports._from = 'من';
exports._of = 'من'; // we have to change the way the parser work in this case, to make the following syntax work: "for (let item from array) doSomething();"
exports._in = 'في';
exports._as = 'ك';
exports._yield = 'انتج';
exports._async = 'لا_تزامن';
exports._await = 'انتظر';
exports._get = 'احضر';
exports._set = 'عين';

exports._package = 'حزمة';
exports._private = 'خاص';
exports._protected = 'محمي';
exports._public = 'عام';
exports._static = 'ثابت';
exports._enum = 'تعداد';
exports._interface = 'واجهة';
exports._type = 'نوع';
exports._implements = 'تنفيذ';

// this should be a reversed defined variable in strict mode
// make sure that these are the same in the APIs translation maps
exports._arguments = 'وسائط';
exports._eval = 'قدر'; // this depends on `this`
exports._constructor = 'منشئ';
exports._require = 'استدعي';
