#!/usr/bin/env bash

task=$1
path=$INIT_CWD
pkg=$(command -v jq > /dev/null \
  && jq '.name' < "$path/package.json" \
  || echo "$path")

declare -A emojis

emojis["linting"]=📝
emojis["building"]=📦
emojis["testing"]=🔍
emojis["formatting"]=📑
emojis["watching"]=👀
emojis["analyzing"]=📈

echo "┏━━━━━ ${emojis[$task]} $task: $pkg ━━━━━━━━━━━━━━━━━━━━━━━━━━"
